name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_jobs:
    runs-on: ubuntu-18.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World"
          
      - name: the time is
        run: |
          date
      
      - name: directory content
        run: |
          ls -l
